/*
This program will do the following:
1. Create 3 separate ArrayLists to store subject, object, and verb words, respectively
    a. Prompt the user to type in some subject, verb and object words to store in the ArrayList
2. Ask the user if they want to generate a sentence
3. If the user responds yes, output a sentence by randomly selecting one subject, verb, and object
4. Printing out the resulting sentence.

Process:
1. Initialize variables:
    a. "ArrayList<String> subjects" to store subject words
    b. "ArrayList<String> objects" to store object words
    c. "ArrayList<String> verbs" to store verb words
    d. "Random random" to randomly select an index in the ArrayList
    e. "String response" to store the user's response
    f. "Scanner input" to prompt the user
2. Set up a loop to fill the subject ArrayList
    FOR int i = 1 to 5 inclusive
        Ask the user to type a noun to be used as a subject
        Add the user's response to the subject ArrayList
    ENDFOR
3. Repeat step 2, but for the object ArrayList
    FOR int i = 1 to 5 inclusive
        Ask the user to type a noun to be used as an object
        Add the user's response to the object ArrayList
    ENDFOR
4. Repeat step 2, but for the verb ArrayList
    FOR int i = 1 to 5 inclusive
        Ask the user to type a noun to be used as a verb
        Add the user's response to the verb ArrayList
    ENDFOR
5. Ask the user if they want to create a sentence
    IF user responds "y"/"Y" THEN
        Concatenate elements from the three ArrayLists based on three index numbers generated by random
        Print out the concatenated elements
    ENDIF
6. Print out the contents of the ArrayLists
 */

import java.util.*;

public class MadLibs {
    public static void main (String[] args) {
        ArrayList<String> subjects = new ArrayList<String>();
        ArrayList<String> objects = new ArrayList<String>();
        ArrayList<String> verbs = new ArrayList<String>();
        Random random = new Random();
        String response = "";
        Scanner input = new Scanner(System.in);

        for (int i = 1; i <= 3; i++) {
            System.out.print("Enter a noun to be used as a subject (" + i + "/3): ");
            response = input.nextLine();
            subjects.add(response);
        }
        System.out.println();

        for (int i = 1; i <= 3; i++) {
            System.out.print("Enter a noun to be used as an object (" + i + "/3): ");
            response = input.nextLine();
            objects.add(response);
        }
        System.out.println();

        for (int i = 1; i <= 3; i++) {
            System.out.print("Enter a verb (" + i + "/3): ");
            response = input.nextLine();
            verbs.add(response);
        }
        System.out.println();

        System.out.print("Do you want to create a sentence (y/n)? ");
        response = input.nextLine();

        if (response.equalsIgnoreCase("y")) {
            System.out.println("Here is your sentence: ");
            System.out.println(subjects.get(random.nextInt(subjects.size())) + " " +
                    verbs.get(random.nextInt(verbs.size())) + " " + objects.get(random.nextInt(objects.size())));
        }
        System.out.println(subjects.toString());
        System.out.println(objects.toString());
        System.out.println(verbs.toString());
    }
}
